service: toolbox

provider:
  name: google
  runtime: python38
  project: your-gcp-project-id
  region: europe-west-1

plugins:
  - serverless-google-cloudfunctions
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  hello:
    handler: handler.handler
    environment:  # Environment variables specific to this function
      FUNCTION_SPECIFIC_VAR: "This is specific to the 'hello' function"
    
